name: Methflow
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12.9
  - minimap2=2.28
  - winnowmap
  - samtools
  - whatshap
  - pysam
  - bedtools
  - nanoporetech::modkit
  - htslib
  - r-base=4.4.2
  - r-sys>=3.4.1  # for running DSS script
  - r-r.utils>=2.5.0  # for running DSS script
  - r-devtools
  - bioconductor-dss=2.54.0
  - pip
  - pip:
      - flash-attn
      # - h5py==3.13.0
      # - mappy==2.28
      # - numpy==2.2.4
      # - pandas==2.2.3
      # - polars==0.20.31
      # - pysam==0.23.0
      # - scikit-learn==1.6.1
      # - torch==2.6.0
